### ISSUE TITLE
Can't edit settings

### ISSUE THREAD

**Issue by saschagehlich** [TheSavior/SublimeJSCSFormatter#11]
When I try to edit my configuration via the command pallette -> `JSCSFormatter: Set node path`, an empty file pops up and the console says:

```
Unable to open /Users/sash/Library/Application Support/Sublime Text 3/Installed Packages/JSCS-Formatter.sublime-package/JSCSFormatter.sublime-settings
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 304, in on_activated
    callback.on_activated(v)
  File "trailing_spaces in /Users/sash/Library/Application Support/Sublime Text 3/Installed Packages/TrailingSpaces.sublime-package", line 419, in on_activated
  File "trailing_spaces in /Users/sash/Library/Application Support/Sublime Text 3/Installed Packages/TrailingSpaces.sublime-package", line 440, in freeze_last_version
  File "./codecs.py", line 885, in open
NotADirectoryError: [Errno 20] Not a directory: '/Users/sash/Library/Application Support/Sublime Text 3/Installed Packages/JSCS-Formatter.sublime-package/JSCSFormatter.sublime-settings'
```

**Comment by brakmic** [comment]
Just go to your AppData/Roaming/Sublime.../InstalledPackages and unpack the **JSCSFormatter.sublime-package**. To unpack it use 7zip, for example.

Then edit the _JSCSFormatter.sublime-settings_ file. Afterwards create a new "zip file" called _JSCSFormatter.sublime-package_ but do neither choose any compression nor put the "packed" files in a directory. Just select all files and create a "save only" package. Then replace the older package with the new one.

**Comment by elicwhite** [comment]
Oh, interesting. Thanks for the report. Definitely a bug. I'll explore what the correct way to handle plugin settings is.

**Comment by brakmic** [comment]
Thanks! :+1:
