### ISSUE TITLE
JSCS-Formatter Error: module.js:338

### ISSUE THREAD

**Issue by janagaprobert** [TheSavior/SublimeJSCSFormatter#33]
I can't get it and need help for this error.
Error: module.js:338
 throw err;
error: cannot find module 'C:\Users\Robert'
  at function.Module._resolveFilename (module.js:336:15)
  at function.Module._load(module.js:278:25)
  at function.Module.runMain(module.js:501:10)
  at startup (node.js:129:16)
  at node.js:814:3

**Comment by mrjoelkemp** [comment]
Duplicate of https://github.com/TheSavior/SublimeJSCSFormatter/issues/14.
