### ISSUE TITLE
Starting node-red with PM2 on Windows: Unexpected token ILLEGAL

### ISSUE THREAD

**Issue by arakno76** [TheSavior/SublimeJSCSFormatter#43]
Hi there,
when I try to PM2 start node-red I get the following error:

`SyntaxError: Unexpected token ILLEGAL
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:413:25)
    at Object.Module._extensions..js (module.js:452:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function._load (C:\Users\Arakno\AppData\Roaming\npm\node_modules\pm2\node_modules\pmx\lib\transaction.js:62:21)
    at Object.<anonymous> (C:\Users\Arakno\AppData\Roaming\npm\node_modules\pm2\lib\ProcessContainerFork.js:46:21)
    at Module._compile (module.js:434:26)
    at Object.Module._extensions..js (module.js:452:10)
    at Module.load (module.js:355:32)
`

**Comment by mrjoelkemp** [comment]
Hi!  Thanks for reporting. I'm not sure how this is related to the plugin. Can you provide some thoughts to help clarify? 

I'll close for now until we get more information. Happy to reopen if this turns out to be a bug in the plugin.

**Comment by arakno76** [comment]
Ok, which kind of info do you need?

**Comment by mrjoelkemp** [comment]
Any ideas on how is this related to the JSCS-Formatter plugin would be helpful. 

Neither Pm2, node-red, nor the stracktrace point to this plugin causing any issues. 

Did you try executing a command through this plugin that caused the issue? 

Did you file this issue on the wrong repo?

**Comment by arakno76** [comment]
Sorry, I'm very newbie to theese topics... I'm only trying to launch node-red via PM2, writing "pm2 start node-red" in win cmd shell. It starts but, after a few minutes, if i PM2 status, then I see that node-red status is "errrored" and in the logs you can see the stacktrace I pasted before... should I do any configuration? I get the same error by typing pm2 start node-red -i max
Thanks!

**Comment by arakno76** [comment]
ok now I got the meaning of your words... sorry I submitted it in the wrong repo!!!!

**Comment by mrjoelkemp** [comment]
Thanks for the info. Yes, please file an issue with https://github.com/Unitech/pm2 or ask on stackoverflow. 

Glad we could point you in the right direction! Cheers!

**Comment by arakno76** [comment]
Cheers!
